### ISSUE TITLE
Any plan for fabric support?

### ISSUE THREAD

**Issue by CRD716** [waffle-stomper/Ghostwriter#24]
I would like to use this with a fabric mod, and was wondering if this would ever be in fabric? I understand it's harder to make a fabric mod, but being lightweight is nice.

**Comment by waffle-stomper** [comment]
@CRD716 - I don't currently have plans to add a Fabric version. I barely have time to keep the Forge version updated, (e.g. Ghostwriter 1.16.1 was released ~6 months after Forge 1.16.1). 

I'd be happy to answer any questions about the Forge version if you're thinking about porting it yourself.

I think the only major changes you'd have to make are in [Ghostwriter.java](https://github.com/waffle-stomper/Ghostwriter/blob/master/src/main/java/wafflestomper/ghostwriter/Ghostwriter.java) where it swaps the vanilla book GUIs for their Ghostwriter equivalents. I'm using Forge events that won't be available in Fabric.

**Comment by nebspacefarer** [comment]
I have released an alternative for Ghostwriter on Fabric, this is not a port but it has been inspired by it in the big lines.
As you do not have any plan to create a Fabric port, here is a link to it that might help you redirect people who asks you: [Stendhal on Modrinth](https://modrinth.com/mod/stendhal)

Your mod has been a great source of inspiration, thank you.

**Comment by waffle-stomper** [comment]
@nebspacefarer - Thank you for your kind words and for making me aware of your project. Stendhal looks pretty cool. I like the sign and chat integrations. 

Have you thought about making it open source?

I've added a note to the Ghostwriter readme that should direct Fabric users your way.

**Comment by nebspacefarer** [comment]
@waffle-stomper Thank you!

Of course I have, the FAQ is mentioning why it is not open source yet:

_A: As of now, nowhere. This project has been a precious opportunity to make myself comfortable again with Java and a good learning process for modding, as much as I would love some help and see how people could contribute in amazing ways, I still want to practice and learn more for future mods.
I don't exclude opening the source code later down the line!_

I will also add a mention of Ghostwriter to redirect Forge users to your project as well.
