### ISSUE TITLE
Ghostwriter bypasses the 15 character title length limit

### ISSUE THREAD

**Issue by waffle-stomper** [waffle-stomper/Ghostwriter#26]
I'm not sure if this also works on vanilla servers, but it seems to work on Spigot 1.16.1 

Steps to reproduce:

1. Save a book to create a .ghb file
2. Open the file in an external text editor and set the title line to:
`title:This is more than 15 characters`
3. Save the file
4. Load the file with ghostwriter and paste it into a new book
5. Click 'Sign'
6. Note that the title extends off the page. You can delete characters, but you can't add any more.
7. Click 'Sign and Close'

**Comment by Lodish** [comment]
Err is this a bug? I thought this was a feature. Copying a book and pasting also gets past the title length limit. In 1.12 Ghostwriter you could bypass the title length limit just by entering a longer title and signing a book normally.

**Comment by waffle-stomper** [comment]
I completely forgot that used to be a feature. I'll add it back in, (#33).

Thanks for reminding me!
