### ISSUE TITLE
update to 1.16.4

### ISSUE THREAD

**Issue by Artin-13** [waffle-stomper/Ghostwriter#37]
**Is your feature request related to a problem? Please describe.**
when i try to use 1.16.1 version game doesn't work

**Describe the solution you'd like**
an update to 1.16.4

**Comment by waffle-stomper** [comment]
@Artin-13 

Thanks for using Ghostwriter! I've just uploaded the 1.16.4 version for you: https://github.com/waffle-stomper/Ghostwriter/releases/download/1.16.4-2.2.9/1.16.4-Ghostwriter-2.2.9.jar
