### ISSUE TITLE
Ghostwriter Has Class Loading Errors On Startup

### ISSUE THREAD

**Issue by ghost** [waffle-stomper/Ghostwriter#39]
soon after the game started the game displays a messages saying that Ghostwriter Has Class Loading Errors

[debug.log](https://github.com/waffle-stomper/Ghostwriter/files/6555770/debug.log)

I did not have any mods apart from Ghostwriter

**Comment by ghost** [comment]
nvm i was using 1.16.5 forge with a too new version of forge mod loader so i used a older one for 1.16.5 so i was using forge
36.1.(i cant remember lol but it was alot newer that 36.1.4) 36.1.34 is the one that works :)

**Comment by waffle-stomper** [comment]
@Foxxy-01 - Thanks for the follow-up!
