### ISSUE TITLE
1.17 update

### ISSUE THREAD

**Issue by KMatias123** [waffle-stomper/Ghostwriter#40]
please

**Comment by waffle-stomper** [comment]
Don't worry - the 1.17 update is coming (eventually). Work is taking up all of my time and energy right now, but I haven't forgotten about Ghostwriter.

**Comment by waffle-stomper** [comment]
Alpha 1.17.1 release here: https://github.com/waffle-stomper/Ghostwriter/releases/tag/1.17.1-2.3.2
