### ISSUE TITLE
Please add version 1.16.5!

### ISSUE THREAD

**Issue by TheGrandJaggard** [waffle-stomper/Ghostwriter#46]
**Is your feature request related to a problem? Please describe.**
The problem is that there is no version 1.16.5. Almost all mods worth adding to my modpack do not have versions 1.16.1-1.16.4, and this mod looks really great and I want to add it.

**Describe the solution you'd like**
I would like you to  update your version 1.16.4 to version 1.16.5.

**Describe alternatives you've considered**
If this can't happen then there will just be sucky books in my modpack and my sister will get really frustrated when she tries to write something then forgets to save it.

**Additional context**
No additional context.

**Comment by waffle-stomper** [comment]
I thought I'd missed 1.16.5 too, but it turns out it was just hidden below the other 1.16 versions: https://github.com/waffle-stomper/Ghostwriter/releases/tag/1.16.5-2.2.6

Enjoy!

**Comment by TheGrandJaggard** [comment]
Thanks a lot! Both for your solution and for your quick response!
