### ISSUE TITLE
Formatting selected text deletes it

### ISSUE THREAD

**Issue by ZeliotL** [waffle-stomper/Ghostwriter#47]
Formatting selected text deletes it, you select the text you want to give a new format, click one of the format buttons and the text just gets deleted. I expected it to keep the text in the book and only format that section i selected.

forge version
1.18.2 - 40.2.0

mod version
[[Beta][1.18.2] v2.3.7 for Forge 1.18.2-40.0.3]

**Comment by waffle-stomper** [comment]
Thanks for the bug report. This has been fixed in release v1.18.2-2.4.2: https://github.com/waffle-stomper/Ghostwriter/releases/tag/v1.18.2-2.4.2
