### ISSUE TITLE
Crashes in File Browser 1.20.2

### ISSUE THREAD

**Issue by DraconicNEO** [waffle-stomper/Ghostwriter#49]
**Describe the bug**
When opening the File Browser on 1.20.2 the game displays saving world text and crashes.

**To Reproduce**
1. Open the menu
2. Click on 'File Browser'
3. Crash

**Expected behavior**
Should open the file browser to allow saving or loading of saved books

**Screenshots**
N/A

**Forge Version:**
e.g. 48.1.0 MC 1.20.2

**Ghostwriter Version (the name of the jar file):**
1.20-Ghostwriter-2.4.5.jar 

**Additional context:**

**Comment by waffle-stomper** [comment]
Thanks for letting me know. I'll work on getting the 1.20.1-4 versions of the mod released soon.

**Comment by waffle-stomper** [comment]
Hi, I've just released a version for 1.20.2. Please try it out:

https://github.com/waffle-stomper/Ghostwriter/releases/tag/v1.20.2-2.4.7
