### ISSUE TITLE
Question(s) 

### ISSUE THREAD

**Issue by Fireworkstars46** [waffle-stomper/Ghostwriter#50]
Can I use this mod to edit book and quills and go back lines in it without delete text?

**Comment by waffle-stomper** [comment]
Hi, Ghostwriter is just a wrapper around the normal book and quill, so you can use the mouse and arrow keys to move around the text without deleting it.

Please note that the latest version I've released is for Minecraft 1.20.0 and it isn't compatible with later versions. I'll try to get those released soon.

**Comment by Fireworkstars46** [comment]
I'm on the 1.12.2 version but ok.

**Comment by Fireworkstars46** [comment]
> Hi, Ghostwriter is just a wrapper around the normal book and quill, so you can use the mouse and arrow keys to move around the text without deleting it.
> 
> 
> 
> Please note that the latest version I've released is for Minecraft 1.20.0 and it isn't compatible with later versions. I'll try to get those released soon.

How exactly do I edit the text without deleting it like you said here?
