### ISSUE TITLE
Update to 1.20.1 - FL 47.2.0 or later

### ISSUE THREAD

**Issue by PSGitHubUser1** [waffle-stomper/Ghostwriter#51]
Everything is in the title

**Comment by waffle-stomper** [comment]
Hi, a lot has changed in Minecraft code between versions 1.20 and 1.20.1.

I'll try to get to it soon.

**Comment by PSGitHubUser1** [comment]
Ok

**Comment by waffle-stomper** [comment]
Hi,

I've released a version for 1.20.1: https://github.com/waffle-stomper/Ghostwriter/releases/tag/v1.20.1-2.4.6
